package com.exam;
// Generated Feb 10, 2019 9:12:52 AM by Hibernate Tools 4.3.1

import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

    private int id;
    @NotEmpty
    @Pattern(regexp = "[a-zA-z]{2,20}$", message = "Name must be atleast 2 characters")
    private String name;
    @NotEmpty
    @Pattern(regexp = "[a-zA-z0-9_]+[@][a-z]+[.][a-z]{2,3}$", message = "Invalid email")
    private String email;
    private String password;

    public Login() {
    }

    public Login(int id) {
        this.id = id;
    }

    public Login(int id, String name, String email, String password) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
